# Generated by Django 4.0.3 on 2022-03-25 06:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9999)),
                ('date', models.DateField(default=datetime.date(2022, 3, 25))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='product name')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='quantity in kg/ltr', max_digits=40, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='amount in TK', max_digits=9999)),
                ('date', models.DateField(default=datetime.date(2022, 3, 25))),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.expenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_number', models.IntegerField(default=0, verbose_name='meal number')),
                ('guest_meal', models.IntegerField(default=0, verbose_name='guest meal number')),
                ('total_meal', models.IntegerField(default=0, verbose_name='total meal number')),
                ('date', models.DateField(default=datetime.date(2022, 3, 25))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
