# Generated by Django 4.0.3 on 2022-03-25 11:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0003_alter_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 25)),
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('date', 'user')},
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('date', 'user'), name='user_unique_day_meal'),
        ),
    ]
