# Generated by Django 4.0.3 on 2022-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_alter_addbalance_date_alter_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
