# Generated by Django 4.0.3 on 2022-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_totalexpenses_rename_total_amount_expenses_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalexpenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000),
        ),
        migrations.AddField(
            model_name='totalexpenses',
            name='created_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='totalexpenses',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
