# Generated by Django 4.0.3 on 2022-04-01 04:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0011_alter_meal_unique_together_alter_addbalance_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalExpenses',
        ),
        migrations.AlterField(
            model_name='addbalance',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 1)),
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 1), null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 1)),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='amount in TK', max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 1)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='quantity in kg/ltr', max_digits=6, null=True),
        ),
    ]
