# Generated by Django 4.0.3 on 2022-04-02 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0012_delete_totalexpenses_alter_addbalance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbalance',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 2), null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(help_text='amount in TK'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='quantity in kg/ltr', null=True),
        ),
    ]
